spring.application.name=

#Base de datos.
spring.datasource.primary.jdbc-url=
spring.datasource.primary.username=
spring.datasource.primary.password=
spring.datasource.primary.driver-class-name=

#Base de datos 2.
spring.datasource.secondary.jdbc-url=
spring.datasource.secondary.username=
spring.datasource.secondary.password=
spring.datasource.secondary.driver-class-name=

# JPA principal
spring.jpa.show-sql=
spring.jpa.database-platform=

#Puerto.
server.port=

#Donde se mandan las imagenes
storage.path=
spring.servlet.multipart.max-file-size=

#Correo
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=
spring.mail.properties.mail.smtp.starttls.required=